<?php

namespace App\Models\admin;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
// use Kyslik\ColumnSortable\Sortable;

class Driver extends Eloquent
{
    use HasFactory;
    // use Sortable;

    protected $collection = 'drivers';

   // protected $Sortable  = [
        // 'driver_first_name','driver_last_name','driver_mobile_no',
        // 'driver_email','vehicle_year','driver_vehicle_registration_number',
        // 'driver_vehicle_make','driver_vehicle_model','driver_vehicle_category',
        // 'driver_puc_expiry_date','driver_dob','driver_blood_group','driver_emergency_number',
        // 'driver_state','driver_city','driver_postal_code','driver_address','driver_profile_picture',
        // 'driver_upload_commercial_insurance','driver_license_front','driver_license_back','driver_aadhaar_front',
        // 'driver_aadhaar_back','driver_rental_agreement_front','driver_rental_agreement_back',
        // 'driver_pan_card','driver_vehicle_registration_image','driver_status','driver_ride_type',
        // 'mondaystartend','tuesdaystartend','wednesdaystartend','thursdaystartend','fridaystartend','saturdaystartend',
        //   'first_name',
        //   'last_name',
        //   'date_of_birth',
        //   'blood_group',
        //   'address',
        //   'block',
        //   'floor',
        //   'unit',
        //   'street',
        //   'city',
        //   'state',
        //   'city',
        //   'postal_code',
        //   'email',
        //   'currency',
        //   'balance',
        //   'vehicle_year',
        //   'vehicle_mileage',
        //   'nric_number',
        //   'referral_code',
        //   'is_referred',
        //   'referred_by',
        //   'referred_by_type',
        //   'license_number',
        //   'license_expiry_date',
        //   'phone_number_country',
        //   'phone_number_country_code',
        //   'phone_number',
        //   'emergency_number_country_code',
        //   'emergency_number',
        //   'photo',
        //   'registration_photo',
        //   'license_photo_front',
        //   'license_photo_back',
        //   'ph_license',
        //   'pdvl',
        //   'pan_card',
        //   'commercial_insurance',
        //   'nric_image_front',
        //   'nric_image_back',
        //   'aadhaar_image_front',
        //   'aadhaar_image_back',
        //   'rental_agreement_front',
        //   'rental_agreement_back',
        //   'car_registration_number',
        //   'car_passenger_capacity',
        //   'ph_decal_number',
        //   'verify_token',
        //   'is_available',
        //   'is_shift_started',
        //   'latitude',
        //   'longitude',
        //   'heading',
        //   'status',
        //   'document_status',
        //   'access_token',
        //   'device_id',
        //   'device_type',
        //   'device_info',
        //   'razorpay_account_id',
        //   'razorpay_account_status',
        //   'api_log',
        //   'total_referral',
        //   'ride_earning',
        //   'ride_cash_earning',
        //   'ride_cash_received',
        //   'earning_owe_to_six',
        //   'toll_earning',
        //   'referral_earning',
        //   'bonus_earning',
        //   'total_earning',
        //   'earning_paid',
        //   'earning_balance',
        //   'last_login',
        //   'avg_rating',
        //   'build_version',
        //   'socket_status',
        //   'socket_id',
        //   'suspended_at',
        //   'created_at',
        //   'updated_at',
        //   'mondaystartend',
        //   'tuesdaystartend',
        //   'wednesdaystartend',
        //   'thursdaystartend',
        //   'fridaystartend',
        //   'saturdaystartend',
        //   'model_id',
        //   'brand_id',
        //   'category_id',

    //];
    protected $fillable = [
        //'driver_first_name','driver_last_name','driver_mobile_no',
        // 'driver_email','vehicle_year','driver_vehicle_registration_number',
        // 'driver_vehicle_make','driver_vehicle_model','driver_vehicle_category',
        // 'driver_puc_expiry_date','driver_dob','driver_blood_group','driver_emergency_number',
        // 'driver_state','driver_city','driver_postal_code','driver_address','driver_profile_picture',
        // 'driver_upload_commercial_insurance','driver_license_front','driver_license_back','driver_aadhaar_front',
        // 'driver_aadhaar_back','driver_rental_agreement_front','driver_rental_agreement_back',
        // 'driver_pan_card','driver_vehicle_registration_image','driver_status','driver_ride_type',
        // 'mondaystartend','tuesdaystartend','wednesdaystartend','thursdaystartend','fridaystartend','saturdaystartend',
          'first_name',
          'last_name',
          'date_of_birth',
          'blood_group',
          'address',
          'block',
          'floor',
          'unit',
          'street',
          'city',
          'state',
          'city',
          'postal_code',
          'email',
          'currency',
          'balance',
          'vehicle_year',
          'vehicle_mileage',
          'nric_number',
          'referral_code',
          'is_referred',
          'referred_by',
          'referred_by_type',
          'license_number',
          'license_expiry_date',
          'phone_number_country',
          'phone_number_country_code',
          'phone_number',
          'emergency_number_country_code',
          'emergency_number',
          'photo',
          'registration_photo',
          'license_photo_front',
          'license_photo_back',
          'ph_license',
          'pdvl',
          'pan_card',
          'commercial_insurance',
          'nric_image_front',
          'nric_image_back',
          'aadhaar_image_front',
          'aadhaar_image_back',
          'rental_agreement_front',
          'rental_agreement_back',
          'car_registration_number',
          'car_passenger_capacity',
          'ph_decal_number',
          'verify_token',
          'is_available',
          'is_shift_started',
          'latitude',
          'longitude',
          'heading',
          'status',
          'document_status',
          'access_token',
          'device_id',
          'device_type',
          'device_info',
          'razorpay_account_id',
          'razorpay_account_status',
          'api_log',
          'total_referral',
          'ride_earning',
          'ride_cash_earning',
          'ride_cash_received',
          'earning_owe_to_six',
          'toll_earning',
          'referral_earning',
          'bonus_earning',
          'total_earning',
          'earning_paid',
          'earning_balance',
          'last_login',
          'avg_rating',
          'build_version',
          'socket_status',
          'socket_id',
          'suspended_at',
          'created_at',
          'updated_at',
          'mondaystartend',
          'tuesdaystartend',
          'wednesdaystartend',
          'thursdaystartend',
          'fridaystartend',
          'saturdaystartend',
          'model_id',
          'brand_id',
          'category_id',

    ];



    public function driver_vehicle_category()
    {
        // print_r("dhfkadf");
        return $this->belongsTo(VehicleCategory::class,'category_id','id');
    }



// }

    }
